"""Analyze differences between textstat and py-readability scores.

This script loads the `_flesch_score.csv` files generated by
`analytics/flesch_score_comparison.py`, quantifies how far the two readability
metrics diverge, and reports descriptive statistics plus Cliff's delta to
capture the magnitude of disagreement between the distributions.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Optional

import numpy as np
import pandas as pd


DATASETS = {
	"agents": "agents_flesch_score_strip.csv",
	"claude": "claude_flesch_score_strip.csv",
	"copilot-instructions": "copilot-instructions_flesch_score_strip.csv",
}

DATASETS_DIR = Path(__file__).resolve().parent.parent / "datasets"


def cliffs_delta(sample_a: Iterable[float], sample_b: Iterable[float]) -> Optional[float]:
	"""Compute Cliff's delta to estimate effect size between two samples."""

	a = np.asarray([value for value in sample_a if pd.notna(value)], dtype=float)
	b = np.asarray([value for value in sample_b if pd.notna(value)], dtype=float)
	if not len(a) or not len(b):
		return None
	diff = a[:, None] - b  # Broadcast differences
	return float(np.sign(diff).sum() / diff.size)


def interpret_cliffs(delta: Optional[float]) -> str:
	"""Translate Cliff's delta into the usual qualitative labels."""

	if delta is None:
		return "n/a"
	abs_delta = abs(delta)
	if abs_delta < 0.147:
		return "negligible"
	if abs_delta < 0.33:
		return "small"
	if abs_delta < 0.474:
		return "medium"
	return "large"


def load_dataset(dataset_name: str, filename: str) -> pd.DataFrame:
	"""Load a dataset and compute per-repository differences."""

	path = DATASETS_DIR / filename
	df = pd.read_csv(path)
	df = df.dropna(subset=["textstat_score", "py_readability_score"])
	df = df.copy()
	df["difference"] = df["textstat_score"] - df["py_readability_score"]
	df["abs_difference"] = df["difference"].abs()
	df["dataset"] = dataset_name
	return df


def summarize_dataset(dataset_name: str, df: pd.DataFrame) -> Dict[str, object]:
	"""Produce summary statistics for a single dataset."""

	stats = {
		"dataset": dataset_name,
		"rows": len(df),
		"mean_diff": df["difference"].mean(),
		"median_diff": df["difference"].median(),
		"std_diff": df["difference"].std(ddof=0),
		"mean_abs_diff": df["abs_difference"].mean(),
		"max_abs_diff": df["abs_difference"].max(),
		"cliffs_delta": cliffs_delta(df["textstat_score"], df["py_readability_score"]),
	}
	stats["effect_size"] = interpret_cliffs(stats["cliffs_delta"])
	return stats


def report_top_outliers(df: pd.DataFrame, limit: int = 5) -> pd.DataFrame:
	"""Return the repositories with the largest absolute disagreement."""

	columns = [
		"repository_owner",
		"repository_name",
		"textstat_score",
		"py_readability_score",
		"difference",
	]
	return df.nlargest(limit, "abs_difference")[columns]


def format_summary_table(summary_rows: List[Dict[str, object]]) -> pd.DataFrame:
	"""Build a nicely formatted summary table."""

	summary_df = pd.DataFrame(summary_rows)
	numeric_cols = [
		"mean_diff",
		"median_diff",
		"std_diff",
		"mean_abs_diff",
		"max_abs_diff",
		"cliffs_delta",
	]
	for col in numeric_cols:
		if col in summary_df:
			summary_df[col] = summary_df[col].map(lambda x: f"{x:.3f}" if pd.notna(x) else "n/a")
	return summary_df


def main() -> None:
	all_dfs: List[pd.DataFrame] = []
	summaries: List[Dict[str, object]] = []

	for name, filename in DATASETS.items():
		print(f"\n=== {name.title()} dataset ===")
		df = load_dataset(name, filename)
		if df.empty:
			print("No comparable rows (missing scores). Skipping...")
			continue
		all_dfs.append(df)
		summaries.append(summarize_dataset(name, df))

		print(f"Rows compared: {len(df)}")
		print(report_top_outliers(df).to_string(index=False))

	if all_dfs:
		combined = pd.concat(all_dfs, ignore_index=True)
		summaries.append(summarize_dataset("combined", combined))
		print("\n=== Combined summary ===")
		print(report_top_outliers(combined).to_string(index=False))

	print("\n=== Summary statistics ===")
	print(format_summary_table(summaries).to_string(index=False))


if __name__ == "__main__":
	main()
